name: Jyoti kumari
description: Frontend Engineer<br>

logo: https://github.com/profile.png?size200

<br><br>

<a href ="https://www.linkedin.com/in/jyoti-kumari-17b250194/">linkdin profile</a><br>

theme: jekyll-theme-minimal
