#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Jyoti kumari

# Short bio or description (displayed in the header)
description: Frontend Engineer<br>
avatar: "/progile.png?size=200
<br><br>

 <a href ="https://www.linkedin.com/in/jyoti-kumari-17b250194/">linkdin profile</a><br>

theme: jekyll-theme-minimal
